<?php
    $order = $block->getOrder();
    $shipping = $block->getOrder()->getShippingMethod();

    if($shipping == "glovo_glovo"){ 
        if(!empty($order->getIdglovo())){
?>
<style type="text/css">.rowlabel-glovo-first{font-weight: bold;}#popup-modal-glovo-vexsoluciones table{margin-bottom: 20px;}#popup-modal-glovo-vexsoluciones {margin-bottom: 40px;}</style>
<div id="popup-modal-glovo-vexsoluciones" style="display: none;">
    <h2><?= __("Shipping by Glovo") ?></h2>
    <table>
        <tr class="rowlabel-glovo">
            <td class="rowlabel-glovo-first"><?= __("Status") ?>:</td><td class="rowlabel-glovo-value" id="glovoingorden"></td>
        </tr>
        
    </table>
    <div id="popup-modal-glovo">
        <div id="popup-modal-glovo-mapa" style="height: 450px;">

        </div>
        <div id="popup-modal-glovo-labels" style="margin-top:20px;">

            

        </div>
    </div>
</div>
<?php }else{
    echo "";
} } ?>

<script type="text/javascript">

    require(
    [
        'jquery',
        'ko',
        'Magento_Ui/js/modal/modal',
        'mage/translate'
    ],
    function(
        $,
        ko,
        modal
    ) {

        var map = null;
        var marker1 = null;
        var route = null;

        var destinolat = null;
        var destinolng = null;

        var actuallat = null;
        var actuallng = null;

        var directionDisplay = null;
        var directionsService;

        var nombrecourier = "";
        var telefonocourier = "";

        var imagen='<?= $this->getViewFileUrl('VexShipping_Glovo::image/scooter.png') ?>';
        var imagentienda='<?= $this->getViewFileUrl('VexShipping_Glovo::image/imagen_tienda.png') ?>';

        $(document).ready(function(){
            var key = "<?= $block->getApiKey() ?>";
            $.getScript("https://maps.googleapis.com/maps/api/js?v=3&sensor=false&key="+key, function () {     
                initialize();
            });

            function initialize(){

                directionsService =new google.maps.DirectionsService();
                directionsDisplay =new google.maps.DirectionsRenderer();


                //jQuery(".vertrackingglovo").click(function(){
                        
                    $.get( window.checkout.baseUrl+"rest/V1/GlovoDelivery",{glovo:"<?= $order->getIdglovo() ?>"} ,function( data ) {
                        
                        jQuery("#glovoingorden").html(data[0].datos_orden.state);
                        jQuery('#popup-modal-glovo-vexsoluciones').show();
                        if(data[0].datos_orden.state=="ACTIVE" || data[0].datos_orden.state=="DELIVERED"){
                            
                            setTimeout(function(){

                                destinolat = parseFloat(data[0].datos_orden.addresses[1].lat);
                                destinolng = parseFloat(data[0].datos_orden.addresses[1].lon);

                                actuallat = parseFloat(data[0].tracking.lat);
                                actuallng = parseFloat(data[0].tracking.lon);

                                let uluru1 = {lat: actuallat, lng: actuallng};
                                let uluru2 = {lat: destinolat, lng: destinolng};
                                map = new google.maps.Map(document.getElementById('popup-modal-glovo-mapa'), {
                                  zoom: 11,
                                  center: uluru1
                                });
                                
                                actmapa({lat: actuallat,lng:actuallng},data[0].contacto.courierName,data[0].contacto.phone);
                                nombrecourier = data[0].contacto.courierName;
                                telefonocourier = data[0].contacto.phone;

                                makeMarker3({lat: parseFloat(data[0].latitud),lng:parseFloat(data[0].longitud)});
                                

                            },1000);
                        }else{
                            $("#popup-modal-glovo-mapa").hide();
                        }
                           
                    },'json');
                        
                        
                //});
                
                function actmapa(coords, nombre, telefono){

                    actuallat = coords.lat;
                    actuallng = coords.lng;

                    var request ={
                        origin:{lat:actuallat,lng:actuallng},
                        destination:{lat:destinolat,lng:destinolng},
                        travelMode: google.maps.TravelMode.DRIVING
                    };
                    
                    directionsService.route(request,function(result, status){
                        
                        if(status == google.maps.DirectionsStatus.OK){

                            if(directionDisplay!=null){
                                directionDisplay.setMap(null);
                            }
                            if(marker1!=null){
                                marker1.setMap(null);
                            }
                            directionDisplay = new google.maps.DirectionsRenderer({
                                map: map,
                                directions: result,
                                suppressMarkers: true
                            });

                            

                            var leg = result.routes[0].legs[0];
                            makeMarker(leg.start_location, nombre, telefono);
                            makeMarker2(leg.end_location);
                            calcularkm();
                        }
                    });

                    
                }
                function makeMarker(position, nombre, telefono) {
                    let icon = new google.maps.MarkerImage(
                        imagen,
                        new google.maps.Size(45, 45),
                        new google.maps.Point(0, 0),
                        new google.maps.Point(0, 0)
                    )
                    marker1 = new google.maps.Marker({
                        position: position,
                        map: map,
                        icon: icon
                    });

                    /*var contentString = nombre+"<br>"+telefono;//+"<br>"+"a 3km de distancia llega en aprox 30'";
                    var infowindow = new google.maps.InfoWindow({
                        content: contentString
                    });

                    infowindow.open(map, marker1);*/
                }
                function makeMarker2(position) {

                    new google.maps.Marker({
                        position: position,
                        map: map
                    });
                }

                function makeMarker3(position) {

                    let icon3 = new google.maps.MarkerImage(
                        imagentienda,
                        new google.maps.Size(50,50),
                        new google.maps.Point(0, 0),
                        new google.maps.Point(0, 0)
                    )

                    let markertienda = new google.maps.Marker({
                        position: position,
                        map: map,
                        icon: icon3
                    });
                }

                function calcularkm(){
                    var service = new google.maps.DistanceMatrixService();
                    service.getDistanceMatrix(
                      {
                        origins: [{lat: actuallat, lng: actuallng}],
                        destinations: [{lat: destinolat, lng: destinolng}],
                        travelMode: 'DRIVING',
                        unitSystem: google.maps.UnitSystem.METRIC,
                        avoidHighways: true,
                        avoidTolls: true,
                      }, callback);
                }
                function callback(response, status) {
                    console.log(response)
                    if(status == 'OK'){

                        if(response.rows[0].elements[0].status=='OK'){

                            var contentString = "<div style='text-align:center;'>"+nombrecourier+"<br><a href='tel:"+telefonocourier+"'>"+telefonocourier+"</a><br>"+"<?= __('to') ?> "+response.rows[0].elements[0].distance.text+" <?= __('away') ?><br> <?= __('arrives in approx') ?> "+response.rows[0].elements[0].duration.text+"</div>";
                            var infowindow = new google.maps.InfoWindow({
                                content: contentString
                            });

                            infowindow.open(map, marker1);
                            
                            
                        }else{
                            var contentString = "<div style='text-align:center;'>"+nombrecourier+"<br><a href='tel:"+telefonocourier+"'>"+telefonocourier+"</a><br></div>";
                            var infowindow = new google.maps.InfoWindow({
                                content: contentString
                            });

                            infowindow.open(map, marker1);
                        }
                    }         
                }
            }

        });
    }
);

</script>